### ISSUE TITLE
Movie feature

### ISSUE THREAD

**Issue by ckchmod** [shinwookang/rbn-matlab#9]
I want to be able to save movies. So I guess I'll work on adding a movie feature...Because I'm selfish..

**Comment by darthbeeblebrox** [comment]
Can we get Grant in on some of that?

**Comment by ckchmod** [comment]
I'll e-mail him.

**Comment by ghost** [comment]
Good idea! I found a cool swirly pattern that would make a nice video.

**Comment by ckchmod** [comment]
Wasn't getting any e-mail response, so I ended up doing the movie feature. . It's pushed. You can generate the movie when you plot it. 

Example:
a.plotCells(true, .5)

means save the movie (true) and with parameter dt = .5. The FPS for the movie is 1/dt.
